"""styles

Revision ID: 9525057a0706
Revises: 605c9198c69d
Create Date: 2021-06-08 16:53:10.696858

"""
from alembic import op
import sqlalchemy as sa
import lore


# revision identifiers, used by Alembic.
revision = '9525057a0706'
down_revision = '605c9198c69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraphs', sa.Column('style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paragraphs', 'style')
    # ### end Alembic commands ###
