"""init

Revision ID: fe89830c858a
Revises: 
Create Date: 2021-05-24 22:39:49.874422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe89830c858a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('stub', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('root_node_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['root_node_id'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaigns_stub'), 'campaigns', ['stub'], unique=True)
    op.create_table('pages',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('stub', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_pages_permalink'), 'pages', ['permalink'], unique=False)
    op.create_index(op.f('ix_pages_public_id'), 'pages', ['public_id'], unique=False)
    op.create_index(op.f('ix_pages_stub'), 'pages', ['stub'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('aliases',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('stub', sa.String(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('alias_id'),
    sa.UniqueConstraint('stub'),
    sa.UniqueConstraint('stub')
    )
    op.create_table('campaign_membership',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'user_id')
    )
    op.create_table('page_links',
    sa.Column('page_from', sa.Integer(), nullable=False),
    sa.Column('page_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_from'], ['pages.page_id'], ),
    sa.ForeignKeyConstraint(['page_to'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('page_from', 'page_to')
    )
    op.create_table('paragraphs',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.Column('edited_on', sa.DateTime(), nullable=True),
    sa.Column('edit_comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('parent_tag_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['parent_tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('page_tags',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('page_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_tags')
    op.drop_table('tags')
    op.drop_table('paragraphs')
    op.drop_table('page_links')
    op.drop_table('campaign_membership')
    op.drop_table('aliases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pages_stub'), table_name='pages')
    op.drop_index(op.f('ix_pages_public_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_permalink'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_campaigns_stub'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
